#!/bin/sh

set -e 

cd "$(dirname "${BASH_SOURCE[0]}")"

docker-compose pull --include-deps --parallel
docker-compose build --pull --no-cache --force-rm --parallel
docker-compose up
docker-compose down -v --remove-orphans

